### PR TITLE
fix: duplicate meta tags

### LINKED ISSUE #777: meta data is doubled/tripled at runtime
Might be related to the closed issue https://github.com/vuejs/vuepress/issues/665.

It was fixed for the `description` tag - the issue seems to persist for other meta tags:

```js
// config.js
  head: [
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:site', content: '@TweetsOfSumit' }],
    ['meta', { name: 'twitter:creator', content: '@TweetsOfSumit' }],
    ['meta', { property: 'og:type', content: 'article' }],
    ['meta', { property: 'og:title', content: 'Raum.sh' }],
    ['meta', { property: 'og:site_name', content: 'Raum.sh' }],
    ['meta', { property: 'og:url', content: 'https://raum.sh' }],
    [
      'meta',
      {
        property: 'og:image',
        content: 'https://raumsh-idpjzzfqhw.now.sh/images/speaking.jpg',
      },
    ],
  ],
```

``` md
---
# Markdown Front Matter
layout: Post
published: 2018-08-07
title: Blog is online 🙋‍♂️
meta:
  - property: og:title
    content: Blog is online 🙋‍♂️
  - name: description
    content: I finally decided to use VuePress as a blog engine.
  - name: keywords
    content: Web Developer Developer Relations Development Blog
---
```
(yup, social meta tags are a bit of a chaos but that's a different issue)

Output:
```html
  <title>Blog is online 🙋‍♂️ | Raum.sh</title>
  <meta name="description" content="I finally decided to use VuePress as a blog engine.">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@TweetsOfSumit">
  <meta name="twitter:creator" content="@TweetsOfSumit">
  <meta property="og:type" content="article">
  <meta property="og:title" content="Raum.sh">
  <meta property="og:site_name" content="Raum.sh">
  <meta property="og:url" content="https://raum.sh">
  <meta property="og:image" content="https://raumsh-idpjzzfqhw.now.sh/images/speaking.jpg">
  <meta name="title" content="Blog is online 🙋‍♂️">
  <meta property="og:title" content="Blog is online 🙋‍♂️">
  <meta name="keywords" content="Web Developer Developer Relations Development Blog">
```

Demo:
https://raum.sh/blog/BlogLaunch.html

Here, the meta tag `og:title` is present three times.

### PR DESCRIPTION
**Pull request by ludanxer**
**Summary**

leave meta tags updating to [updateMeta.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js)

fix #777 , relate to #2153 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

I'm not sure what to do when page meta is conflict with site meta, for example

```js
// config.js
  head: [
    ['meta', { name: 'test-meta', content: 'this is a head meta' }]
  ]
```

```
---
# Markdown Front Matter
meta:
  - name: test-meta
    content: this is a page meta
---
```
[merge them](https://stackoverflow.com/questions/6531761/multiple-meta-tags-with-the-same-name) or use page meta to override site meta like `description`

### CODE REVIEW

**Comment by kefranabg** [comment]
Hi @ludanxer,

Thanks for the PR.

Here you're just removing the current page meta tags 😅

But what we would like is replacing the global meta tags with the current page meta tags if page meta tags exists. The solution would be a merge, with a priority on page meta tags.

**Comment by ludanxer** [comment]
@kefranabg Thanks for your review and sorry for the delay.

I think I'm just removing one set of page meta tags. I understand how things look like, so I'll try to explain what I'm trying to do.

### Head meta tags

Head meta tags are inserted differently in `dev` and `build`.

#### dev

https://github.com/vuejs/vuepress/blob/606ae4af8e9ea6de3134653d89d3429ae70c1580/packages/%40vuepress/core/lib/node/dev/index.js#L169

#### build

https://github.com/vuejs/vuepress/blob/606ae4af8e9ea6de3134653d89d3429ae70c1580/packages/%40vuepress/core/lib/client/index.ssr.html#L9

### Page meta tags

Page meta tags are managed by [updateMeta.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js) in both `dev` and `build`. However, another set of page meta tags are inserted by SSR.

#### dev

[updateMeta.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js)

#### build

Both https://github.com/vuejs/vuepress/blob/606ae4af8e9ea6de3134653d89d3429ae70c1580/packages/%40vuepress/core/lib/client/index.ssr.html#L10
and [updateMeta.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js) which is causing the duplicate.

**Comment by kefranabg** [comment]
I just made a test with your branch, and global meta tag are always taking priority on page meta tag. It should be the opposite 😄 

If global meta tags and page meta tag are defined, page meta tag have priority

**Comment by ludanxer** [comment]
Need some time to fix that. Thanks!

**Comment by nuochong** [comment]
I also found this problem. These problems (# 112, # 565, # 665, # 2133) two years ago seem to be finally fixed.
There is no problem in dev mode, it will appear after packaging. When the page template is packaged, the meta tag is written. The meta here is the meta tag of ssr. Due to the characteristics of the spa, the content in the head will not be refreshed, and after manually switching pages, a new meta tag will be dynamically added to the head. Causes meta tag confusion. Affects applications such as twitter, such as:
`` `html
<meta name = "twitter: image" content = "a.png">
<meta name = "twitter: image" content = "b.png">
`` `
The above example will result in two pictures for twitter sharing
Solution:
1. Overwrite when writing the meta dynamically. The meta permission of the current page is higher than the meta permission of the ssr loading page. (May increase the amount of calculation)
2. Delete meta tag write in ssr (may not be good for seo)

**Comment by ludanxer** [comment]
I made a [test branch](https://github.com/ludanxer/vuepress/tree/fix/double-meta-test) and [deploy](https://double-meta.netlify.com) it. Hope it helps.

And I noticed

```js
watch: {
  $page () {
     this.updateMeta()
  }
}
```

Keeps getting triggered when I scroll past headers in a page

**Comment by nuochong** [comment]
Thank you for your efforts

**Comment by kefranabg** [comment]
Hey, I made some tests, if I add a the meta tag `keywords` on a page, I can't see it in the meta tag on the generated HTML page. Note that it will be added on runtime, but not on build time.

For example:

```
---
meta:
  - name: description
    content: hello
  - name: keywords
    content: super duper SEO
---
```

- build the vuepress site
- go to dist/path/to/my-page-with-meta
- `description` will be generated in the html page but not `keywords`

Let me know if you want more context

**Comment by ludanxer** [comment]
I think it's ready now 🤔Thanks for the patience ❤️

**Comment by kefranabg** [comment]
@ludanxer Sorry for the delay, I'll do a review ASAP 😉

File: packages/@vuepress/core/lib/client/root-mixins/updateMeta.js [hunk 1]
```diff
@@ -1,38 +1,53 @@
...
+    this.currentMetaTags = [...document.querySelectorAll('meta')]
+
+    // indirectly init siteMetaTags from DOM
+    this.siteMetaTags = this.currentMetaTags.map(element => {
+      const siteMeta = {}
+      for (const attribute of element.attributes) {
+        siteMeta[attribute.name] = attribute.value
+      }
+      return siteMeta
+    })
```
Comment (kefranabg) [inline packages/@vuepress/core/lib/client/root-mixins/updateMeta.js]:
```suggestion
    this.siteMetaTags = this.currentMetaTags.map(metaTag =>
      metaTag.attributes.reduce((acc, { name, value }) => ({
        ...acc,
        [name]: value
      }), {}))
```

File: packages/@vuepress/core/lib/client/root-mixins/updateMeta.js [hunk 2]
```diff
@@ -1,38 +1,53 @@
...
-      if (descriptionMetas.length) {
-        descriptionMetas.forEach(m => this.currentMetaTags.add(m))
-      }
+      const newMetaTags = this.getMergedMetaTags(this.siteMetaTags)
+      this.currentMetaTags = updateMetaTags(newMetaTags, this.currentMetaTags)
+    },
 
-      this.currentMetaTags = new Set(updateMetaTags(meta, this.currentMetaTags))
+    getMergedMetaTags (siteMeta) {
+      const pageMeta = (this.$page.frontmatter.meta || []).slice(0)
```
Comment (kefranabg) [inline packages/@vuepress/core/lib/client/root-mixins/updateMeta.js]: What's the goal of this `slice(0)`?

File: packages/@vuepress/core/lib/node/build/index.js [hunk 3]
```diff
@@ -77,9 +77,11 @@ module.exports = class Build extends EventEmitter {
     })
 
     // pre-render head tags from user config
+    // filter out meta tags for they will be injected in updateMeta.js
     this.userHeadTags = (this.context.siteConfig.head || [])
+      .filter(item => item[0] !== 'meta')
       .map(renderHeadTag)
-      .join('\n  ')
+      .join('\n    ')
```
Comment (kefranabg) [inline packages/@vuepress/core/lib/node/build/index.js]: Why an extra space?

File: packages/@vuepress/core/lib/node/build/index.js [hunk 4]
```diff
@@ -77,9 +77,11 @@ module.exports = class Build extends EventEmitter {
     })
 
     // pre-render head tags from user config
+    // filter out meta tags for they will be injected in updateMeta.js
     this.userHeadTags = (this.context.siteConfig.head || [])
+      .filter(item => item[0] !== 'meta')
```
Comment (kefranabg) [inline packages/@vuepress/core/lib/node/build/index.js]:
```suggestion
      .filter(([headTagType]) => headTagType !== 'meta')
```

File: packages/@vuepress/core/lib/node/build/index.js [hunk 5]
```diff
@@ -138,14 +140,10 @@ module.exports = class Build extends EventEmitter {
...
 
-    // #565 Avoid duplicate description meta at SSR.
-    const meta = (page.frontmatter && page.frontmatter.meta || []).filter(item => item.name !== 'description')
-    const pageMeta = renderPageMeta(meta)
-
     const context = {
       url: page.path,
       userHeadTags: this.userHeadTags,
-      pageMeta,
+      pageMeta: null,
```
Comment (kefranabg) [inline packages/@vuepress/core/lib/node/build/index.js]: is this property still required?

File: packages/@vuepress/core/lib/client/root-mixins/updateMeta.js [hunk 6]
```diff
@@ -1,38 +1,53 @@
...
+      // pageMetaTags have higher priority than siteMetaTags
+      // description needs special attention for it has too many entries
```
Comment (kefranabg) [inline packages/@vuepress/core/lib/client/root-mixins/updateMeta.js]:
```suggestion
      // description needs special attention as it has too many entries
```

File: packages/@vuepress/core/lib/client/root-mixins/updateMeta.js (hunk 1 above)
Comment (ludanxer) [reply packages/@vuepress/core/lib/client/root-mixins/updateMeta.js]: Sorry, I just realize that I'm init siteMetaTags with entry-page meta tags instead of site meta tags. Fixed in https://github.com/vuejs/vuepress/pull/2164/commits/a853352c166623500b5a89a8c3bb8fa58e8416e4

File: packages/@vuepress/core/lib/node/build/index.js (hunk 3 above)
Comment (ludanxer) [reply packages/@vuepress/core/lib/node/build/index.js]: Unify the indent (4 spaces) inside `<head>`

```html
<html>
  <head>
    <meta name="description" content="Vue-powered Static Site Generator">
    ...
  </head>
```

File: packages/@vuepress/core/lib/client/root-mixins/updateMeta.js [hunk 7]
```diff
@@ -64,3 +76,35 @@ function updateMetaTags (meta, current) {
...
+ * @param {Array} meta
+ * @returns {Array<string>}
+ */
+
+function renderPageMeta (meta) {
+  if (!meta) return ''
+  return meta.map(m => {
+    let res = `<meta`
+    Object.keys(m).forEach(key => {
+      res += ` ${key}="${m[key]}"`
```
Comment (kleisauke) [inline packages/@vuepress/core/lib/client/root-mixins/updateMeta.js:106]: Shouldn't this be escaped? For example, this `config.js`:
```js
module.exports = {
  description: 'Image cache & resize service',
}
```

renders as (within version 1.4.1):
```html
    <meta name="description" content="Image cache & resize service">
```

which [is probably not correct](https://stackoverflow.com/a/20585780/10952119). fwiw, version 1.4.0 didn't had this problem.

Suggestion:
```suggestion
      res += ` ${key}="${escape(m[key])}"`
```
and this import at the top of the file:
```js
const escape = require('escape-html')
```
