### PR TITLE
fix($shared-utils): use title variable for homepage (fix #2247)

### LINKED ISSUE #2247: Make it possible to set homepage title
#### What problem does this feature solve?
It gives the ability to change home page title.
#### What does the proposed API look like?
It's not going to change API.
#### How should this be implemented in your opinion?
Imagine you want to use [homepage option](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage) so you set `home: true` then you search something that exist on homepage:
Screen Shot 1399-01-05 at 16 12 41
It is shown as `Home` and you can **not** change homepage title because when `home` is `true` it's hard coded and I don't know why:
https://github.com/vuejs/vuepress/blob/7977532d5a0d67509b25c1a788f236cd6e312ae5/packages/%40vuepress/shared-utils/src/inferTitle.ts#L12-L14
#### Are you willing to work on this yourself?
Yes.

### PR DESCRIPTION
**Pull request by Alizadeh118**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: packages/@vuepress/shared-utils/src/inferTitle.ts [hunk 1]
```diff
@@ -9,11 +9,10 @@ import deeplyParseHeaders from './deeplyParseHeaders'
  */
 
 export = function (frontmatter: Record<string, any>, strippedContent: string): string | void {
-  if (frontmatter.home) {
-    return 'Home'
-  }
   if (frontmatter.title) {
     return deeplyParseHeaders(frontmatter.title)
+  } else if (frontmatter.home) {
```
Comment (meteorlxy) [inline packages/@vuepress/shared-utils/src/inferTitle.ts:14]: the `else` here is redundant

Comment (Alizadeh118) [reply packages/@vuepress/shared-utils/src/inferTitle.ts:14]: Yeah, my bad! 🙈
How can I fix it? Should I make another PR?

Comment (meteorlxy) [reply packages/@vuepress/shared-utils/src/inferTitle.ts:14]: Just push to the same branch, and current PR will update
