### PR TITLE
fix($markdown): Fix four spaces codeblocks rendering (Closes #1921)

### LINKED ISSUE #1921: Four spaces codeblock is rendered different than three backsticks codeblock on small devices
- [x] I confirm that this is an issue rather than a question.

## Bug report

Three backsticks codeblock takes full container width while four spaces codeblock has some space on left and right.

[Check this image](https://i.imgur.com/1i98Qkv.png)

#### Steps to reproduce

1) Create a three backsticks codeblock
2) Create a four spaces codeblock
3) Change your browser screen size or access through phone
4) Compare

#### What is expected?

Both should be the same width

#### What is actually happening?

Three backsticks codeblock is being rendered inside a div with the classes `language-<language>` and `extra-class`, the pre tag also has an `language-<language>` class

#### Other relevant information

- Removing the `language-<language>` class from the outside div fixes it but the box isn't rounded.

### PR DESCRIPTION
**Pull request by pyaillet**
**Summary**

Fix #1921 

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

File: packages/@vuepress/markdown/lib/preWrapper.js [hunk 1]
```diff
@@ -8,12 +8,15 @@
...
-  md.renderer.rules.fence = (...args) => {
+  const wrap = (wrapped) => (...args) => {
     const [tokens, idx] = args
     const token = tokens[idx]
-    const rawCode = fence(...args)
+    const rawCode = wrapped(...args)
     return `<!--beforebegin--><div class="language-${token.info.trim()} extra-class">`
     + `<!--afterbegin-->${rawCode}<!--beforeend--></div><!--afterend-->`
   }
+  const fence = md.renderer.rules.fence
```
Comment (kefranabg) [inline packages/@vuepress/markdown/lib/preWrapper.js]: Actually, I think you could make a small improvement :

```
const { fence, codeBlock } =  md.renderer.rules
md.renderer.rules.fence = wrap(fence)
md.renderer.rules.code_block = wrap(codeBlock)
```

What do you think @pyaillet ?

Comment (pyaillet) [reply packages/@vuepress/markdown/lib/preWrapper.js]: I need to rename `codeBlock` to `code_block` to do this.
And sadly, the linter doesn't like it:
```
vuepress/packages/@vuepress/markdown/lib/preWrapper.js
  18:18  error  Identifier 'code_block' is not in camel case  camelcase

✖ 1 problem (1 error, 0 warnings)
```

Comment (kefranabg) [reply packages/@vuepress/markdown/lib/preWrapper.js]: Oh sure, I missed that 😉
